name: Create Pull Request

on:
  push:
    branches:
      - main
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pushes Translate file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.MY_PAT }}
        with:
          source_file: "src/translations"
          destination_repo: "khole/epico-client"
          destination_folder: "src/translations"
          user_email: ${{ secrets.USER_EMAIL }}}
          user_name: ${{ secrets.USER_NAME }}}
          commit_message: "A custom message for the commit"
